IF OBJECT_ID(N'ac.ORCHESTRATOR_CONFIG', N'U') IS NULL
BEGIN
    CREATE TABLE [ac].[ORCHESTRATOR_CONFIG]
    (
        [ID] INT IDENTITY(1,1) NOT NULL PRIMARY KEY,
        [ORCHESTRATOR_ID] NVARCHAR(100) NOT NULL,
        [NAME] NVARCHAR(200) NOT NULL,
        [DESCRIPTION] NVARCHAR(MAX) NULL,
        [INTENT_KEYWORDS] NVARCHAR(MAX) NULL,
        [IS_ACTIVE] BIT NOT NULL CONSTRAINT [DF_ORCHESTRATOR_CONFIG_IS_ACTIVE] DEFAULT(1),
        [SORT_ORDER] INT NOT NULL CONSTRAINT [DF_ORCHESTRATOR_CONFIG_SORT_ORDER] DEFAULT(0),
        [NO_MATCH_POLICY] NVARCHAR(20) NOT NULL CONSTRAINT [DF_ORCHESTRATOR_CONFIG_POLICY] DEFAULT('fail'),
        [CREATED_AT] DATETIME2(7) NOT NULL CONSTRAINT [DF_ORCHESTRATOR_CONFIG_CREATED_AT] DEFAULT(SYSUTCDATETIME()),
        [UPDATED_AT] DATETIME2(7) NOT NULL CONSTRAINT [DF_ORCHESTRATOR_CONFIG_UPDATED_AT] DEFAULT(SYSUTCDATETIME())
    );
END;
GO

IF NOT EXISTS (SELECT 1 FROM sys.indexes WHERE name = 'UX_ORCHESTRATOR_CONFIG_ORCHESTRATOR_ID' AND object_id = OBJECT_ID(N'ac.ORCHESTRATOR_CONFIG'))
BEGIN
    CREATE UNIQUE INDEX [UX_ORCHESTRATOR_CONFIG_ORCHESTRATOR_ID]
    ON [ac].[ORCHESTRATOR_CONFIG] ([ORCHESTRATOR_ID]);
END;
GO

IF OBJECT_ID(N'ac.ORCHESTRATOR_AGENT_MAP', N'U') IS NULL
BEGIN
    CREATE TABLE [ac].[ORCHESTRATOR_AGENT_MAP]
    (
        [ID] INT IDENTITY(1,1) NOT NULL PRIMARY KEY,
        [ORCHESTRATOR_ID] NVARCHAR(100) NOT NULL,
        [AGENT_ID] NVARCHAR(100) NOT NULL,
        [DOMAIN_HINT] NVARCHAR(400) NULL,
        [PRIORITY] INT NOT NULL CONSTRAINT [DF_ORCHESTRATOR_AGENT_MAP_PRIORITY] DEFAULT(0),
        [IS_ACTIVE] BIT NOT NULL CONSTRAINT [DF_ORCHESTRATOR_AGENT_MAP_IS_ACTIVE] DEFAULT(1),
        [CREATED_AT] DATETIME2(7) NOT NULL CONSTRAINT [DF_ORCHESTRATOR_AGENT_MAP_CREATED_AT] DEFAULT(SYSUTCDATETIME()),
        [UPDATED_AT] DATETIME2(7) NOT NULL CONSTRAINT [DF_ORCHESTRATOR_AGENT_MAP_UPDATED_AT] DEFAULT(SYSUTCDATETIME())
    );
END;
GO

IF NOT EXISTS (SELECT 1 FROM sys.indexes WHERE name = 'UX_ORCHESTRATOR_AGENT_MAP_ORCH_AGENT' AND object_id = OBJECT_ID(N'ac.ORCHESTRATOR_AGENT_MAP'))
BEGIN
    CREATE UNIQUE INDEX [UX_ORCHESTRATOR_AGENT_MAP_ORCH_AGENT]
    ON [ac].[ORCHESTRATOR_AGENT_MAP] ([ORCHESTRATOR_ID], [AGENT_ID]);
END;
GO

IF NOT EXISTS (SELECT 1 FROM sys.foreign_keys WHERE name = 'FK_ORCHESTRATOR_AGENT_MAP_ORCHESTRATOR')
BEGIN
    ALTER TABLE [ac].[ORCHESTRATOR_AGENT_MAP]
    ADD CONSTRAINT [FK_ORCHESTRATOR_AGENT_MAP_ORCHESTRATOR]
        FOREIGN KEY ([ORCHESTRATOR_ID]) REFERENCES [ac].[ORCHESTRATOR_CONFIG] ([ORCHESTRATOR_ID]);
END;
GO
